version: '3.9'

services:
  jenkins:
    build: 
      context: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  build-agent:
    build:
      context: ./build-agent
    container_name: build-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # deployment-agent:
  #   build:
  #     context: ./deployment-agent
  #   container_name: deployment-agent

volumes:
  jenkins_home:
